
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
    expose:
      - 15672
    env_file:
      - ./.env
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbit-net

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - rabbitmq
    ports:
      - 443:443
      - 80:80
    networks:
      - rabbit-net

volumes:
  rabbitmq_data:

networks:
  rabbit-net:

