FROM nginx:1.25.3-alpine

RUN apk add openssl \
    &&  mkdir /etc/nginx/ssl \
    &&  openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx-selfsigned.key -out /etc/nginx/ssl/nginx-selfsigned.crt  -subj "/C=/ST=/L=/O=/CN=" \
    &&  rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/